name: Build Standalone

on: [push]

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
        include:
          - os: windows-latest
          - os: ubuntu-latest
          #- os: macos-latest
            
    env:
      buildDir: '${{ github.workspace }}/build'
      installDir: '${{ github.workspace }}/miind_install'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: lukka/get-cmake@latest
      
      - name: Ubuntu - install dependencies
        run: |
          sudo apt-get install libboost-all-dev libpugixml-dev fftw3-dev freeglut3-dev libgsl0-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev
        if: contains( matrix.os, 'ubuntu')
        
      - name: MacOS - install xquartz for GL support, fftw, and OpenMP support
        run: brew install gcc pugixml boost freeglut gsl boost-python xquartz fftw libomp pkg-config
        if: contains( matrix.os, 'macos')
      
      - name: dir
        run: find $RUNNER_TEMP
        shell: bash
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
        
      - name: Install vcpkg on windows
        # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
          appendedCacheKey: ${{matrix.os}}-build-vcpkg-v2-${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: x64-windows
          doNotCache: true
        if: contains( matrix.os, 'windows')
        
      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ env.buildDir }}'
          cmakeAppendedArgs: '"-GNinja" -DCMAKE_INSTALL_PREFIX=${{ env.installDir }} -DVCPKG_TARGET_TRIPLET=x64-windows'
          buildWithCMake: true
        if: contains( matrix.os, 'windows')
        
        
      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: '${{ env.buildDir }}'
          cmakeAppendedArgs: '"-GNinja" -DCMAKE_INSTALL_PREFIX=${{ env.installDir }} -DCMAKE_BUILD_TYPE=Release'
          buildWithCMake: true
        if: contains( matrix.os, 'macos') || contains( matrix.os, 'ubuntu')
        
        
      - name: Add vcpkg installed bin to path so windows can find files when using MIIND
        run: echo "$VCPKG_ROOT/installed/x64-windows/bin" >> $GITHUB_PATH
        if: contains( matrix.os, 'windows')

      - name: Install MIIND on Linux
        working-directory: ${{ env.buildDir }}  
        run: ninja install
        shell: bash
        if: contains( matrix.os, 'ubuntu')
        
      - name: Check files in Windows install directory
        working-directory: ${{ env.buildDir }}  
        run: ls -la 
        if: contains( matrix.os, 'windows')
        
      - name: Install MIIND on Windows
        working-directory: ${{ env.buildDir }}  
        run: cmake --install .
        shell: bash
        if: contains( matrix.os, 'windows')
        
      - name: Add miindio.py to path
        run: echo '${{ env.installDir }}/share/miind/python' >> $GITHUB_PATH
      - name: Add MIIND_LIBRARY_DIR to ENV
        run: echo "MIIND_LIBRARY_DIR=${{ env.installDir }}/lib" >> $GITHUB_ENV
      - name: Add miind python to PYTHONPATH
        run: echo "PYTHONPATH=${{ env.installDir }}/share/miind/python" >> $GITHUB_ENV
      - name: Add miind includes to CPLUS_INCLUDE_PATH
        run: echo "CPLUS_INCLUDE_PATH=${{ env.installDir }}/include/miind:${{ env.installDir }}/include/miind/GeomLib" >> $GITHUB_ENV
      - name: Add MIIND_INCLUDE_DIR to ENV
        run: echo "MIIND_INCLUDE_DIR=${{ env.installDir }}/include/miind" >> $GITHUB_ENV
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine scikit-build build auditwheel numpy matplotlib==3.2 scipy shapely descartes
        shell: bash
      - name: Run Integration Tests
        working-directory: ${{ github.workspace }}/examples/IntegrationTests 
        run: python system_tests.py
        shell: bash
      
        
        
