name: Build

on: [push]

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04] # macos-10.15 windows-2019
        include:
          #- os: windows-2019
          - os: ubuntu-18.04
          #- os: macos-10.15
          #  triplet: x64-osx-mixed
          #  vcpkgCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
            
    env:
      buildDir: '${{ github.workspace }}/build'
      CIBW_BUILD: cp38-manylinux_x86_64	cp38-win_amd64
      CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
      CIBW_BEFORE_BUILD: pip install scikit-build build auditwheel numpy matplotlib==3.2 scipy shapely descartes
      CIBW_BEFORE_BUILD_LINUX: yum install -y python36-devel ninja-build boost-devel pugixml-devel freeglut-devel gsl-devel libXi-devel mesa-libGL-devel mesa-libGLU-devel libXrandr-devel libXxf86vm-devel fftw-devel
      
      CIBW_BEFORE_BUILD_WINDOWS: choco install visualstudio2017community visualstudio2017-workload-nativedesktop ninja -f -y
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
            cp custom-triplets/*.cmake vcpkg/triplets
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Install cibuildwheel
        run: |
          python -m pip install twine cibuildwheel==1.8.0

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
            

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl    
          
      - name: Publish package
        if: github.event_name == 'push' # && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          #password: ${{ secrets.PYPI_TEST_API_TOKEN }} Add once we can create a secret
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkOGUzMWI0OGYtZjE0ZS00ZGUzLTkxNjEtZmYzZWJkODEyYzgwAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiA5aJXbljJQ0NQRu5Wn9f3v4CB35xhwzauoq72exCLs4A
          packages_dir: ./wheelhouse/
          repository_url: https://test.pypi.org/legacy/